[package]
name = "helius"
version = "0.1.2"
edition = "2021"
description = "An asynchronous Helius Rust SDK for building the future of Solana"
keywords = ["helius", "solana", "asynchronous-sdk", "das", "cryptocurrency"]
repository = "https://github.com/helius-labs/helius-rust-sdk"
docs = "https://docs.rs/helius/latest/helius/"
license = "MIT"
authors = ["0xIchigo <0xIchigo@protonmail.com>"]
readme = "README.md"
homepage = "https://www.helius.dev/"

[dependencies]
reqwest = { version = "0.12.3", features = ["json"] }
serde = "1.0.198"
serde_json = "1.0.116"
solana-sdk = "1.18.11"
thiserror = "1.0.58"
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread", "net"] }
chrono = { version = "0.4.11", features = ["serde"] }
solana-client = "1.18.12"
solana-program = "1.18.12"
serde-enum-str = "0.4.0"
tokio-tungstenite = { version = "0.21.0", features = ["native-tls", "handshake"] }
tokio-stream = "0.1.15"
solana-rpc-client-api = "1.18.12"
futures-util = "0.3.30"
solana-account-decoder = "1.18.12"
solana-transaction-status = "1.18.12"
futures = "0.3.30"
semver = "1.0.23"
url = "2.5.0"

[dev-dependencies]
mockito = "1.4.0"
